//Auth Action Type
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const LOGIN_VALUE_CHANGE = 'LOGIN_VALUE_CHANGE';
export const NORMAL_LOGIN_SUCCESS = 'NORMAL_LOGIN_SUCCESS';
export const NORMAL_LOGIN_FAIL = 'NORMAL_LOGIN_FAIL';
export const REGISTER_VALUE_CHANGE = 'REGISTER_VALUE_CHANGE';
export const NORMAL_REGISTER_SUCCESS = 'NORMAL_REGISTER_SUCCESS';
export const NORMAL_REGISTER_FAIL = 'NORMAL_REGISTER_FAIL'; 
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const LOGIN = 'Login';
export const LOGOUT = 'Logout';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const FORGET_PASSWORD_SCREEN = 'FORGET_PASSWORD_SCREEN';
export const MAIN_SCREEN = 'MAIN_SCREEN';

//Create Profile Action Type
export const CREATE_PROFILE_VALUE_CHANGE = 'CREATE_PROFILE_VALUE_CHANGE';
export const CREATE_PROFILE_SELECT_CAMERA = 'CREATE_PROFILE_SELECT_CAMERA';
export const CREATE_PROFILE_SELECT_LIBRARY = 'CREATE_PROFILE_SELECT_LIBRARY'; 
export const TEXT_INPUT_IS_INVALID = 'TEXT_INPUT_IS_INVALID';
export const CREATE_PROFILE_START = 'CREATE_PROFILE_START';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';

//Create Photo Card Action Type
export const CREATE_PHOTO_CARD_SELECT_CAMERA_FRONT = 'CREATE_PHOTO_CARD_SELECT_CAMERA_FRONT';
export const CREATE_PHOTO_CARD_SELECT_CAMERA_BACK = 'CREATE_PHOTO_CARD_SELECT_CAMERA_BACK';
export const CREATE_PHOTO_CARD_SELECT_LIBRARY_FRONT = 'CREATE_PHOTO_CARD_SELECT_LIBRARY_FRONT';
export const CREATE_PHOTO_CARD_SELECT_LIBRARY_BACK = 'CREATE_PHOTO_CARD_SELECT_LIBRARY_BACK';

//Main Action Type
export const GET_PROFILE_ALL_DATA = 'GET_PROFILE_ALL_DATA'
