//Auth Action Type
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const FACEBOOK_LOGIN_COMMON_ERROR = 'FACEBOOK_LOGIN_COMMON_ERROR';
export const LOGIN_VALUE_CHANGE = 'LOGIN_VALUE_CHANGE';
export const NORMAL_LOGIN_SUCCESS = 'NORMAL_LOGIN_SUCCESS';
export const NORMAL_LOGIN_FAIL = 'NORMAL_LOGIN_FAIL';
export const REGISTER_VALUE_CHANGE = 'REGISTER_VALUE_CHANGE';
export const NORMAL_REGISTER_SUCCESS = 'NORMAL_REGISTER_SUCCESS';
export const CREATE_ACCOUNT_SOCIAL_SUCCESS = 'CREATE_ACCOUNT_SOCIAL_SUCCESS';
export const CREATE_ACCOUNT_SOCIAL_FAIL = 'CREATE_ACCOUNT_SOCIAL_FAIL';
export const ERROR_NETWORK = 'ERROR_NETWORK';
export const NORMAL_REGISTER_FAIL = 'NORMAL_REGISTER_FAIL'; 
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const REGISTER_START_LOADING = 'REGISTER_START_LOADING';
export const LOGIN = 'Login';
export const LOGOUT = 'Logout';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const CREATE_PROFILE_SCREEN = 'CREATE_PROFILE_SCREEN';
export const FORGET_PASSWORD_SCREEN = 'FORGET_PASSWORD_SCREEN';
export const MAIN_SCREEN = 'MAIN_SCREEN';
export const LOGIN_COMMON_ERROR = 'LOGIN_COMMON_ERROR';
export const REGISTER_COMMON_ERROR = 'REGISTER_COMMON_ERROR';

//Create Profile Action Type
export const CREATE_PROFILE_VALUE_CHANGE = 'CREATE_PROFILE_VALUE_CHANGE';
export const CREATE_PROFILE_SELECT_CAMERA = 'CREATE_PROFILE_SELECT_CAMERA';
export const CREATE_PROFILE_SELECT_LIBRARY = 'CREATE_PROFILE_SELECT_LIBRARY'; 
export const TEXT_INPUT_IS_INVALID = 'TEXT_INPUT_IS_INVALID';
export const CREATE_PROFILE_START = 'CREATE_PROFILE_START';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL';
export const CREATE_PROFILE_UPLOAD_IMAGE_SUCCESS = 'CREATE_PROFILE_UPLOAD_IMAGE_SUCCESS';
export const CREATE_PROFILE_UPLOAD_IMAGE_FAIL = 'CREATE_PROFILE_UPLOAD_IMAGE_FAIL';
export const CREATE_PROFILE_COMMON_ERROR = 'CREATE_PROFILE_COMMON_ERROR';

//Create Photo Card Action Type
export const CREATE_PHOTO_CARD_SELECT_CAMERA_FRONT = 'CREATE_PHOTO_CARD_SELECT_CAMERA_FRONT';
export const CREATE_PHOTO_CARD_SELECT_CAMERA_BACK = 'CREATE_PHOTO_CARD_SELECT_CAMERA_BACK';
export const CREATE_PHOTO_CARD_SELECT_LIBRARY_FRONT = 'CREATE_PHOTO_CARD_SELECT_LIBRARY_FRONT';
export const CREATE_PHOTO_CARD_SELECT_LIBRARY_BACK = 'CREATE_PHOTO_CARD_SELECT_LIBRARY_BACK';
export const CREATE_PHOTO_CARD_SKIP_PAGE = 'CREATE_PHOTO_CARD_SKIP_PAGE';
export const CREATE_PHOTO_CARD_START = 'CREATE_PHOTO_CARD_START';
export const CREATE_PHOTO_CARD_UPLOAD_IMAGE_SUCCESS = 'CREATE_PHOTO_CARD_UPLOAD_IMAGE_SUCCESS';
export const CREATE_PHOTO_CARD_UPLOAD_IMAGE_FAIL = 'CREATE_PHOTO_CARD_UPLOAD_IMAGE_FAIL';
export const CREATE_PHOTO_CARD_COMMON_ERROR = 'CREATE_PHOTO_CARD_COMMON_ERROR';

//Main Action Type
export const HOME_START_LOADING = 'HOME_START_LOADING';
export const HOME_GET_PROFILE_DEFAULT_SUCCESS = 'HOME_GET_PROFILE_DEFAULT_SUCCESS'
export const HOME_GET_PROFILE_DEFAULT_FAIL = 'HOME_GET_PROFILE_DEFAULT_FAIL' 
export const HOME_COMMON_ERROR = 'HOME_COMMON_ERROR';
export const HOME_RESET_TO_LOGIN_SCREEN = 'HOME_RESET_TO_LOGIN_SCREEN';
 
