//Auth Action Type
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';
export const LOGIN_VALUE_CHANGE = 'LOGIN_VALUE_CHANGE';
export const NORMAL_LOGIN_SUCCESS = 'NORMAL_LOGIN_SUCCESS';
export const NORMAL_LOGIN_FAIL = 'NORMAL_LOGIN_FAIL';
export const REGISTER_VALUE_CHANGE = 'REGISTER_VALUE_CHANGE';
export const NORMAL_REGISTER_SUCCESS = 'NORMAL_REGISTER_SUCCESS';
export const NORMAL_REGISTER_FAIL = 'NORMAL_REGISTER_FAIL';
export const NORMAL_REGISTER_NOT_MATCH_PASSWORD = 'NORMAL_REGISTER_NOT_MATCH_PASSWORD';
export const LOGIN_USER_START = 'LOGIN_USER_START';
export const REGISTER_USER_START = 'REGISTER_USER_START';
export const LOGIN = 'Login';
export const LOGOUT = 'Logout';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';

//Create Profile Action Type
export const CREATE_PROFILE_VALUE_CHANGE = 'CREATE_PROFILE_VALUE_CHANGE';
export const SELECT_PHOTO_CAMERA = 'SELECT_PHOTO_CAMERA';
export const SELECT_PHOTO_LIBRARY = 'SELECT_PHOTO_LIBRARY';
export const CHOOSE_CAMERA = 0;
export const CHOOSE_LIBRARY = 1;
export const TEXT_INPUT_IS_REQUIRE = 'TEXT_INPUT_IS_REQUIRE';
export const CREATE_PROFILE_START = 'CREATE_PROFILE_START';
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS';
