export default {

  //COLOR 
  NAV_BAR_COLOR: '#339CED',
  TITLE_NAV_BAR_COLOR: '#FFFFFF',
  BACKGROUND_AUTH_CONTAINER_COLOR: '#FFFFFF',
  BACKGROUND_WHITE_COLOR: '#FFFFFF',
  BACKGROUND_CONTAINER_COLOR: '#EDEEEF',
  PLACEHOLDER_TEXT_COLOR: '#B4B4B4',
  INPUT_TEXT_COLOR: '#454545',
  SEPARATOR_COLOR: '#EAEAEA',
  TEXT_SEPARATOR_COLOR: '#454545',
  FORGET_PASSWORD_COLOR: '#B4B4B4',
  TEXT_COLOR: '#454545',
  TEXT_ERROR_COLOR: 'red',
  TEXT_BUTTON_HOME_COLOR: '#2F2F2F',
  TEXT_TITLE_HOME_COLOR: '#2F2F2F',
  ICON_HOME_COLOR: '#2F2F2F',
  SEPARATOR_HOME_COLOR: '#E0E0E0',
  BUTTON_EDIT_HOME_COLOR: '#339CED',

  //FONTSIZE  
  TEXT_SEPARATOR_FONT: 19,
  TEXT_FONT: 19,
  TEXT_FORGET_PASSWORD_FONT: 14,
  TEXT_ERROR_FONT: 16,
  ICON_HOME_FONT: 25,

  //MARGIN
  MARGIN_DEFAULT: 8,
  MARGIN_LEFT: 9,
  MARGIN_RIGHT: 9,
  MARGIN_XX: 16,
  
  //PADDING
  PADDING_DEFAULT: 8,
  PADDING_LEFT: 9,
  PADDING_RIGHT: 9,
  PADDING_XX: 16
};

