export default {

  //COLOR
  NAV_BAR_COLOR: '#339CED',
  TITLE_NAV_BAR_COLOR: '#FFFFFF',
  BACKGROUND_CONTAINER_COLOR: '#FFFFFF',
  PLACEHOLDER_TEXT_COLOR: '#B4B4B4',
  INPUT_TEXT_COLOR: '#454545',
  SEPARATOR_COLOR: '#EAEAEA',
  TEXT_SEPARATOR_COLOR: '#454545',
  FORGET_PASSWORD_COLOR: '#B4B4B4',

  //FONTSIZE  
  TEXT_SEPARATOR_FONT: 19,
  TEXT_FORGET_PASSWORD_FONT: 14,

  //MARGIN
  MARGIN_DEFAULT: 8,
};

